# Generated by Django 4.1.13 on 2025-03-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapasestudiantes',
            name='etapa',
            field=models.CharField(default='1', max_length=6),
        ),
    ]
