# Generated by Django 4.1.13 on 2024-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=True, max_length=32)),
                ('role', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
    ]
