# Generated by Django 4.1.13 on 2024-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=32)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('apellido', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=True)),
                ('user', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=48)),
                ('role', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
