# Generated by Django 4.1.13 on 2024-07-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('seccion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
