# Generated by Django 4.1.13 on 2024-07-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_estudiante_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(max_length=10),
        ),
    ]
