# Generated by Django 4.1.13 on 2024-11-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_estudiante_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ultimo_año_cursado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
