# Generated by Django 4.1.13 on 2024-09-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_estudiante_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_est', models.CharField(max_length=10)),
                ('name_est', models.CharField(max_length=32)),
                ('seccion', models.CharField(max_length=10)),
                ('ref_cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
            options={
                'db_table': 'trayecto4',
            },
        ),
        migrations.CreateModel(
            name='Trayecto3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_est', models.CharField(max_length=10)),
                ('name_est', models.CharField(max_length=32)),
                ('seccion', models.CharField(max_length=10)),
                ('ref_cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
            options={
                'db_table': 'trayecto3',
            },
        ),
        migrations.CreateModel(
            name='Trayecto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_est', models.CharField(max_length=10)),
                ('name_est', models.CharField(max_length=32)),
                ('seccion', models.CharField(max_length=10)),
                ('ref_cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
            options={
                'db_table': 'trayecto2',
            },
        ),
        migrations.CreateModel(
            name='Trayecto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_est', models.CharField(max_length=10)),
                ('name_est', models.CharField(max_length=32)),
                ('seccion', models.CharField(max_length=10)),
                ('ref_cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
            options={
                'db_table': 'trayecto1',
            },
        ),
    ]
