# Generated by Django 4.1.13 on 2024-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectos', '0002_alter_trayecto1_ref_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proyecto', models.FileField(upload_to='proyectos/')),
                ('Capitulos', models.FileField(upload_to='capitulos/')),
                ('Grupo_est_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EtapasEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Estatus', models.CharField(max_length=16)),
                ('Grupo_est_id', models.CharField(max_length=50)),
            ],
        ),
    ]
