# Generated by Django 4.1.13 on 2024-11-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_estudiante_status'),
        ('trayectos', '0003_archivosestudiantes_etapasestudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayectos_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_est', models.CharField(max_length=10)),
                ('name_est', models.CharField(max_length=32)),
                ('seccion', models.CharField(max_length=10)),
                ('trayecto_año', models.CharField(max_length=10)),
                ('codigo_año', models.CharField(max_length=10)),
                ('ref_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
            options={
                'db_table': 'trayectos_all',
            },
        ),
    ]
